version: 2
jobs:
  build:
    machine: true
    working_directory: ~/todolist
    steps:
      - checkout
      - run: docker build --no-cache -t e2e-test .
      - run: docker run -p 80:80 --rm e2e-test

workflows:
  version: 2
  frontend:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
